### ISSUE TITLE
facial recognition is not working on iOS (image)

### ISSUE THREAD

**Issue by ferchhho** [auduno/clmtrackr#103]
I am developing a cross-platforms project (Phonegap) and I try to integrate the clmtrackr but it not responding appropriately on iOS devices but android it is.

Verifying the problem I found that the native method  of JS (getImageData()) is crashing the flow app.

`    var imageData = work_ctx.getImageData(0, 0, w, h);`

**Comment by SalRocco** [comment]
Same problem here

**Comment by auduno** [comment]
WebRTC and getUserMedia is not supported in current versions of iOS, so I think this is the issue you're running into. It will however be supported in iOS 11 which is due to be released this fall.

**Comment by christiandohnert-misterspex** [comment]
This is correct. With the major updates this fall for iOS and macOS the browsers will implement the needed functions. So it is just a matter of time and we have to be patient.

**Comment by ryansit** [comment]
You can now test on Safari easily with https://developer.apple.com/safari/technology-preview/

But you need to update the clmtrackr code to handle the newer navigator.mediaDevices.getUserMedia

**Comment by auduno** [comment]
I'll have a look at updating clmtrackr with support for navigator.mediaDevices.getUserMedia over the next weeks.

**Comment by auduno** [comment]
The examples in `dev` branch are now using `navigator.mediaDevices.getUserMedia`, so should hopefully work fine on iOS once iOS11 is out.
