### ISSUE TITLE
Google chrome crashing after pull request #83

### ISSUE THREAD

**Issue by mccoder** [auduno/clmtrackr#105]
Now WebWorkers created infinitely and after 50 WebWorkers page crashes.  
Google chrome 58.0.3029.110 (64-bit) linux

Page does not crash if you destroy every Worker

```
worker.addEventListener('message', function (e) {
        this.faceDetected(e, callback);
        worker.terminate();
      }.bind(this), false);
```

**Comment by auduno** [comment]
Ouch, that was a nasty bug! Fixed it now, thanks for reporting it!
