### ISSUE TITLE
How to overlay Glasses on face instead of mask ?

### ISSUE THREAD

**Issue by farazirfan47** [auduno/clmtrackr#106]
You work is awesome, I want to overlay glasses on face instead of masks. what do I need to do ? How do I find the points for glasses and fit it to face ?

**Comment by FlowHartigan** [comment]
Thank you for this work ! I would also like to replace the mask with glasses. I have the same questions as @farazirfan47 .

**Comment by christiandohnert-misterspex** [comment]
Have a look here: https://www.misterspex.co.uk/glasses/polo-ralph-lauren-ph-2083-5007_f6476598.html and take a look at the 4th product picture (this includes selecting a picture of your own or take a new one with a webcam). This is an example where clmtrackr is used to look place a pair of glasses onto a face.

**Comment by farazirfan47** [comment]
@christiandohnert-misterspex  how you are so sure they have used clmtrackr ? I think they have used visage SDK flash solution from here http://visagetechnologies.com/

**Comment by christiandohnert-misterspex** [comment]
You used the live try on. That's the one with flash. Click on the icon with the camera

![image](https://user-images.githubusercontent.com/25505243/27239088-c58e50fa-52cf-11e7-80d6-119887cef68e.png)

**Comment by farazirfan47** [comment]
I know it, but this was not my question.

**Comment by christiandohnert-misterspex** [comment]
Sorry then.
For the still images the clmtrackr is used. I fiddled around a little bit with a live video stream a few days ago and it is possible. I will put it up and paste the link here :)

**Comment by christiandohnert-misterspex** [comment]
Here is what I hacked together: https://github.com/christiandohnert-misterspex/tryon

**Comment by farazirfan47** [comment]
Thanks @christiandohnert-misterspex
