### ISSUE TITLE
How to improve light conditions

### ISSUE THREAD

**Issue by aboenemann** [auduno/clmtrackr#107]
clmtrackr only works if the face is lightened very equally. 
Is there an option to adjust this, to allow facial recognition in e.g a bright room? Light comes from left and right equally but the face seems to be too bright to be recognized.

It would be great to receive some help, it is quite urgent unfortunately.

**Comment by auduno** [comment]
Hi, sorry for late reply. By default clmtrackr will try to equalize images that are too dark or too light (via equalize_histogram [here](https://github.com/auduno/clmtrackr/blob/dev/src/facedetector/faceDetection.js#L308)). If this still does not help, you might have to adjust camera settings or do some kind of preprocessing of the images/video, but I think that's a bit outside the scope of clmtrackr.
