### ISSUE TITLE
Detection over photos issue for latest build

### ISSUE THREAD

**Issue by Endur** [auduno/clmtrackr#108]
Hi, Auduno,

since latest merged jsfeat_detect_worker.js I found that the face detection over photos fails usually compared to the release 1.01 (on same photos). It's seems like the initial rectangle around the face isn't defined well.

The detection over video is ok. I have checked the code but wasn't able to find a reason unfortunately... Any idea?

/Endur

**Comment by auduno** [comment]
Hi, thanks for reporting! Do you have examples of images that fail in the new code vs old? I'll try to troubleshoot next week.

**Comment by Endur** [comment]
Am Sun, 28 May 2017 11:43:26 -0700
schrieb Audun Mathias Øygard <notifications@github.com>:

> Hi, thanks for reporting! Do you have examples of images that fail in
> the new code vs old? I'll try to troubleshoot next week.


Good Morning,


thank you for your replay...

Three images are attached, working in 1.01 but not for the current
version. Excepting the me.jpg (it's me really) please don't use them for
public areas.


/Endur

**Comment by Endur** [comment]
ok, will re-sent the images to your private email...

**Comment by auduno** [comment]
Hi,

there was indeed a small bug that I've fixed now (in commit https://github.com/auduno/clmtrackr/commit/ccb2976d9c168db17253cebf42f2f4c09b752abc). That looks to have fixed it, but if not, let me know. Thanks for the example images you sent me, that made debugging easier!
