### ISSUE TITLE
clmtrackr error at line 1088

### ISSUE THREAD

**Issue by VerbalCPU** [auduno/clmtrackr#114]
Hello,

while i try to load the library in my html file when i run it i always get "clmtrackr.js:1088 Uncaught SyntaxError: Unexpected token { ". I searched it and there is nothing wrong with it and if i use the min edition of the library it works just fine.
What could be the solution to this matter?

**Comment by auduno** [comment]
Hi, I just released a new version of clmtrackr a couple of days ago. Could you test out with this version and see if the problem persists?

**Comment by VerbalCPU** [comment]
Hello, now it works fine thank you!

**Comment by auduno** [comment]
Great, thanks!
