### ISSUE TITLE
Cannot set property 'clm' of undefined

### ISSUE THREAD

**Issue by MrShakes** [auduno/clmtrackr#124]
I am trying to run on in an Android App on the device using it's webview (i.e. website to Native, Phonegap).
For that I converted clmtrackr.js to es52015 as I was having problems with it as it was and now I get the error: Cannot set property 'clm' of undefined.
What is the solution please?

Node: 6.10.2
Npm: 3.10.10
OS: MacOS Sierra

**Comment by zachBridges** [comment]
@MrShakes It would be helpful if you could include a snippet of your usage.

I ran across a similar issue; when I installed this library with npm and tried to `require('clmtrackr')`. 
I will assume you're doing something similar; I cannot imagine how 'clm' would be `undefined` if you're including it as a <script>, as the readme indicates.

If you are indeed importing using npm, you can either
`const clm = require('clmtrackr').default`
or
`import clm from 'clmtrackr'`

**Comment by MrShakes** [comment]
@zachBridges sorry, it's been over a year now, I ended up using the native device's face tracking capabilities

**Comment by zachBridges** [comment]
@auduno Will you close, please? Thanks
