### ISSUE TITLE
Detecting neutral emotions 

### ISSUE THREAD

**Issue by adamhipster** [auduno/clmtrackr#129]
I saw that the classifier is based on Ekman, who has no theoretical notion of a neutral emotion. Still, how would one classify a blank stare?

I consider  a blank stare to be a neutral emotion. I'm talking about not moving your facial muscles and it's akin to the :-| emoticon

**Comment by auduno** [comment]
I haven't really based the classifier on any rigorous expression model. However, a simple way to detect neutral emotion is to say that the absence of any other detected emotion is a neutral emotion.
