### ISSUE TITLE
is it possible to detect additional items, like a coin or credit card ?

### ISSUE THREAD

**Issue by tarassych** [auduno/clmtrackr#140]
Or any way to calculate real face size using this tool ?

**Comment by auduno** [comment]
There's not really an easy way to calculate real face size with clmtrackr. With some assumptions about the field of view of the camera, and how far a user will sit from the camera, it's possible to make rough calculations, but these things differ a lot between mobile and desktop. The best option is probably to use a card or coin for scale as you suggest, but there is no built in detector in clmtrackr for those objects.
