### ISSUE TITLE
"Tracking in image" example fails in latest Chrome Version 64.0.3282.119

### ISSUE THREAD

**Issue by trytobesteady** [auduno/clmtrackr#143]
The issue can be observed in the official example:
https://www.auduno.com/clmtrackr/examples/clm_image.html

**Comment by donut87** [comment]
I can confirm this.

**Comment by MariasStory** [comment]
works on 65.

**Comment by donut87** [comment]
65? So the nightly build?

**Comment by Endur** [comment]
Update received for Chrome today: 64.0.3282.167, Fedora Linux. This version is working again as expected.

**Comment by donut87** [comment]
I can confirm this.
;-)

So I think this could be closed.

**Comment by auduno** [comment]
I can confirm it's working in latest official build of Chrome, so I'll close it.
