### ISSUE TITLE
Is there a way to get the face rectangle?

### ISSUE THREAD

**Issue by seranus** [auduno/clmtrackr#144]
I'm wondering is there an easy way to get a face rectangle similarly to other face detectors?

**Comment by donut87** [comment]
This is done first hand during the face detection. See [getBoundingBox](https://github.com/auduno/clmtrackr/blob/63c14656f10c6838f21a887c80b3816ad649a636/src/facedetector/faceDetection.js#L77) to get an idea.
If you want to just have bounding boxes around a face, jsfeat might already solve your problem.
