### ISSUE TITLE
Camera doesn't open in safari.

### ISSUE THREAD

**Issue by veetechh** [auduno/clmtrackr#159]
Trying clm video example in safari. Camera is not opening.

**Comment by donut87** [comment]
Could you be more specific?
Safari:
- mobile/desktop
- version
- version of os

Could you open the console and paste anything (error logs) that might be related to the camera?

**Comment by aullman** [comment]
It's working for me in Safari 12. Make sure you're using at least Safari 11 because webrtc was not supported before that.

**Comment by veetechh** [comment]
Sorry, it is opening the camera, but frames are lagging. Very Slow

**Comment by auduno** [comment]
This issue seems to be the same as #163 , so I'm closing this one. Please post any followup questions or information there instead.
