### ISSUE TITLE
Why I'm not able to run examples/face_deformation_video.html?

### ISSUE THREAD

**Issue by bismoy2013** [auduno/clmtrackr#30]
It keeps on showing "wait..Loading..video". Please help !

**Comment by bismoy2013** [comment]
There are many ways we can view our face by clicking on either of the Unwell or Cheery face button , therefore I was wondering if there is any way that I can save the deformed video in the database .

**Comment by auduno** [comment]
Maybe, but I'm not sure how. You would have to do some kind of screen capture, which I'm not sure if webRTC supports. :/

**Comment by bismoy2013** [comment]
Well, I've been trying to have all the facial changes in the video but those facial modes aren't getting trapped sadly . Thus, I wanted to know solution from you if you could suggest something on it . Tried Webrtc but don't know , as of now , not working .

**Comment by bismoy2013** [comment]
I mean I am able to save video, but just plain video recording , no facial modes are getting stored .

**Comment by auduno** [comment]
No, the facial deforming is done by a webgl canvas that is overlayed the
video, so recording from the video stream won't help. You'll have to blend
the webgl canvas and the video somehow, so I guess you'd have to use some
screen capture solution, but I don't know if such a solution exists.

**Comment by bismoy2013** [comment]
I tried screen capturing, like taking a photo. But for having the complete video part, to my understanding, as you just said, two canvas need to merged into one working video . Am I right ?

**Comment by auduno** [comment]
Yes, that's correct, you'd have merge the two canvases into one video. Did
the screen capture work?

**Comment by bismoy2013** [comment]
Screen capture also gave some trouble, ended up implementing taking the whole screen shot which was clear enough by the way, but merging two canvas ? well no idea yet . perhaps you know something about that part ? :)

**Comment by auduno** [comment]
I don't, sorry. :(

**Comment by bismoy2013** [comment]
If you come across something useful related to this, please do let me know here :) Thanks.

**Comment by keanudicap** [comment]
Hi bismoy2013,

I got the same problem of loading video when using chrome. Can you tell how to fix this problem when running locally?

**Comment by bismoy2013** [comment]
you have to run it as a server from eclipse , also go thru some google app engine tutorials. you will get it.

**Comment by keanudicap** [comment]
Thank you and it works after setting local server.

**Comment by bismoy2013** [comment]
Welcome :) -- Happy coding --
