### ISSUE TITLE
WebGL only?

### ISSUE THREAD

**Issue by 45kb** [auduno/clmtrackr#34]
Hi, sorry for the question, i just don't understand if the library only works on browsers that support WebGL, can you just clarify this to me?

Thank you, this is an amazing project!

**Comment by auduno** [comment]
It should work on browsers without WebGL as well, but the tracking might be a bit slower.

**Comment by 45kb** [comment]
@auduno  ok thanks :)  i am testing the lib on cordova / phonegap , i notice one thing:

 iOS safari v.8 detected all the faces in pics
 while android 4.1 browser do not detect the same faces in the same pics.

 I don't have errors, so i tought it was a matter of webGL, since android  doesn't support webGL.


Anyway, thank you i will try to debug better :)

**Comment by 45kb** [comment]
@auduno  Hi, sorry for interrupting again, i just copied your example (http://auduno.github.io/clmtrackr/clm_image.html) and all the scripts, i find hard to understand which scripts are needed and which not, actually i just need to recognize faces in photos.
Just to be sure, can you just tell me which of these files aren't needed for the scope:

  utils.js

  numeric-1.2.6.min.js
  
  mosse.js
  
  jsfeat-min.js
  
  frontalface.js
  
  jsfeat_detect.js
  
  left_eye_filter.js
  
  right_eye_filter.js
  
  nose_filter.js
  
  model_pca_20_svm.js
  
  clm.js
  
  svmfilter_webgl.js
  
  svmfilter_fft.js
  
  mossefilter.js
  
  Stats.js


Thank you and sorry again

**Comment by auduno** [comment]
If you're just looking to detect faces, you should actually just use [jsfeat](http://inspirit.github.io/jsfeat/) (which is not my library). I've created a wrapper for jsfeat, jsfeat_detect.js, which makes it a bit simpler to use, so you could take a look at that. So you'd just need the files jsfeat-min.js and jsfeat_detect.js.

**Comment by 45kb** [comment]
@auduno thank you a lot :+1:

**Comment by 45kb** [comment]
@auduno  Sorry i am here again, i wanted just to ask you one last thing if possible, i included the jsfeat.min and the jsfeat_detect.js so i did:

var f = new jsfeat_detect(document.getElementById('canvas'));

f.findFace();

console.log(f);


It  works and i get a returned Object in console, which contains data like (confidence, x, y etc..), but i don't understand how to check this data to match a face, may i ask you how you did check this?

Thank you and sorry again

**Comment by auduno** [comment]
The position of the detected face is given by a box with coordinate of top left corner at (x, y) and coordinate of bottom right corner at (x+width, y+height), where the data x, y, width and height is given by the returned object. The returned data "confidence" tells us a score of how sure we are that there is a face in the bounding box, higher scores are better.

Note that in jsfeat_detect.js I only return one face even if there are many faces in the image, I only choose the bounding box with highest confidence score.

**Comment by 45kb** [comment]
@auduno  clear now thank you! Sorry for bothering you

**Comment by gopendra-dwivedi** [comment]
@auduno Hi, 

Can i use this for other object detection and how?

**Comment by auduno** [comment]
Yes, probably, but you'll have to train your own model of the hand using for instance [clmtools](https://github.com/auduno/clmtools). For tracking hands, I think it's better to take a look at [js-objectdetect](https://github.com/mtschirs/js-objectdetect) since it contains a ready-to-go model of hand tracking.
