### ISSUE TITLE
Detect Eyes opened and closed

### ISSUE THREAD

**Issue by JordanMachado** [auduno/clmtrackr#36]
Hi,

thanks for your work. I'm wondering if we could detect when eyes are closed or not. Is it possible ?

**Comment by auduno** [comment]
It might be possible, but I haven't tried it. The face fitting model is not so precise when it comes to details like eyes, so it might be a bit off, but maybe it's worth a try?

You could try training a classifier with the code [here](https://github.com/auduno/clmtools/blob/master/pdm_builder/create_classifier.py), but you need to annotate a few image examples of people with eyes open and eyes closed.

**Comment by JordanMachado** [comment]
I will try to find some classifier for eyes open or close and test it.
Thank you.

**Comment by Alexander-Herranz** [comment]
What is the status of this issue? I'm interested in getting the status (opened/closed) of each eye.

**Comment by JordanMachado** [comment]
It's been a long time but the project has not been released. But we use to have some result but it was not very accurate. Our technique was to detect the eyes first and after render the square of the two eye in another canvas and apply a classifier for close and open. Sadly I can't share you some peace of code.

**Comment by Alexander-Herranz** [comment]
Thanks for the info. I'll develop a classifier to dectect the status, hope the the result pass the test!

**Comment by fernandodrumond** [comment]
I'm looking into the same thing! I've found this tutorial to detect blinking, I'm gonna look into changing it to detect if the eye is open/closed.
https://andrevenancio.com/eye-blink-detection/
@Alexander-Herranz have you found anything on that?

**Comment by Alexander-Herranz** [comment]
@fernandodrumond that tutorial is a great start point. My problem was I didn't have the opened eye previous reference. 
You also can try JsFea:t https://inspirit.github.io/jsfeat/#features2d
Check Yape algorithm to detect points, and you'll see the difference in closed vs opened eyes.

Working on histograms also gives you the key, you'll notice all opened or closed eyes keeps the same histogram figure, respectively but haven't implemented this solution at all yet.


I did my test not over full eye, like Venancio example but only over pupile, cutting the image as follow:

rightEyeRect.x = (pos[63][0]+pos[27][0])/2;
rightEyeRect.y = (pos[63][1]+pos[27][1])/2;
rightEyeRect.w = (pos[64][0]+pos[27][0])/2 - (pos[63][0]+pos[27][0])/2;
rightEyeRect.h = (pos[26][1]+pos[27][1])/2 - (pos[24][1]+pos[27][1])/2;

**Comment by fernandodrumond** [comment]
Thank you @Alexander-Herranz that looks like a good approach, I'm gonna give it a try!
