### ISSUE TITLE
Problem with Tracking facial model example

### ISSUE THREAD

**Issue by JackHsin** [auduno/clmtrackr#37]
Hello, I'm fascinated by your works, but I face a problem.
I download your full package of clmtrackr and try the example inside, the example is like this one:http://auduno.github.io/clmtrackr/example.html
The problem is the green mask doesn't move at all, always stands at the upper left and no coordinates showed below...
No matter how I tired I still couldn't make it. I don't know what I missed...

**Comment by post2seth** [comment]
Are you running that at local server?  Or you are using file:/// to run the
example

On Saturday, March 7, 2015, JackHsin <notifications@github.com> wrote:

> Hello, I'm fascinated by your works, but I face a problem.
> I download your full package of clmtrackr and try the example inside, the
> example is like this one:http://auduno.github.io/clmtrackr/example.html
> The problem is the green mask doesn't move at all, always stands at the
> upper left and no coordinates showed below...
> No matter how I tired I still couldn't make it. I don't know what I
> missed...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/auduno/clmtrackr/issues/37>.
>


-- 
Sent from Gmail iPhone App

**Comment by JackHsin** [comment]
Oh, got it= = it work thanks, but why?

**Comment by post2seth** [comment]
actually in the file:/// mode ajax or file loading do not work, you can
make that working in file mode either with node-webkit( if serving local
app ) OR use local AJAX by modify google chrome config.

- Seth

**Comment by JackHsin** [comment]
Oh learned! Thanks a lot!!!

**Comment by post2seth** [comment]
Welcome

On Saturday, March 7, 2015, JackHsin <notifications@github.com> wrote:

> Oh learned! Thanks a lot!!!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/auduno/clmtrackr/issues/37#issuecomment-77687320>.
>


-- 
Sent from Gmail iPhone App
