### ISSUE TITLE
How to create mosse filter for any other object?

### ISSUE THREAD

**Issue by gautamkishore** [auduno/clmtrackr#38]
Is there a way to generate mosse filter for any other object or it's features like you used for nose, left_eye, right_eye etc? 
I'm sure there must be some code to generate the filters but I'm unable to locate in clmtrackr and the clmtools both.

**Comment by kkateivanova** [comment]
Hey, thanks for the tracker! The same question - I want to create the filter for mouth - can you suggest, how can I do it?

**Comment by auduno** [comment]
Sorry, this should have been done a long time ago, but the code for training the mosse filters is finally published here : https://github.com/auduno/mosse/tree/master/src/filters

Note that there is also a mouth filter trained here : https://github.com/auduno/mosse/blob/master/src/filters/mouth_filter.js

**Comment by gautamkishore** [comment]
Thanks.

**Comment by kkateivanova** [comment]
Thank you!
