### ISSUE TITLE
Error loading masks in Face Substitution example

### ISSUE THREAD

**Issue by CorpusCallosum** [auduno/clmtrackr#43]
I am having a consistent image load problem with the face substitution example. It seems like it is an order of operations issues. My guess is that sometimes the mask image files get loaded before the .load callback is applied to them, and therefore the callback never gets triggered, and the mask canvases never get created. Sometimes they load, sometimes they don't, but so far I have not been able to find a solution.

**Comment by auduno** [comment]
Is this using the face substitution example online, or when running it from your own computer? Did you modify the example in any way?

**Comment by CorpusCallosum** [comment]
This happens to me both when I run it online and locally using a python simple server.

**Comment by CorpusCallosum** [comment]
I was able to resolve the issue by loading the images via JS rather than in the DOM, I can submit a pull request with my fix. BTW I've been testing this on Chrome on a Mac.

**Comment by auduno** [comment]
Yes, do submit a pull request with fix and I'll have a look at it asap.

**Comment by CorpusCallosum** [comment]
Hey I made the fix and submitted the pull request here: https://github.com/auduno/clmtrackr/pull/46
Cheers!

**Comment by auduno** [comment]
Should have merged this ages ago, thanks for the fix!

**Comment by CorpusCallosum** [comment]
Thanks :)

On Thursday, December 10, 2015, Audun Mathias Øygard <
notifications@github.com> wrote:

> Closed #43 <https://github.com/auduno/clmtrackr/issues/43>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/auduno/clmtrackr/issues/43#event-488522440>.
>


-- 
Jack Kalish
www.jackkalish.com

**Comment by CorpusCallosum** [comment]
Jack Kalish loves MUBI and thinks you might love it too.

Every day MUBI's in-house film experts hand-pick a beautiful new film and you have a month to watch it. That means there will always be 30 wonderful cult, classic and award-winning films to enjoy.

Try MUBI for free: https://mubi.com/tell-a-friend/email/1k9wylk?utm_campaign=invitation&utm_source=refer_friend&utm_medium=email
