### ISSUE TITLE
Can we get the name and center position of a detected object ?

### ISSUE THREAD

**Issue by Anthodpnt** [auduno/clmtrackr#49]
Hi,

First of all, thanks for the time you've spent coding this library, it's very useful. 
Although, is there any way to get the name and center position of a specific object ?

I need to know the center position of the mouth for example in order to compare the values with default ones and activate some events if the values are close enough.

The problem is that we currently can't say if the x and y positions came from the mouth, the jawline, the left eye, etc... And we can't know the center position of a specific object.

Is a function like `getCenterPosition('mouth')` possible ? 
This function could return the same array as the `getCurrentPosition()` function but with the x and y values of the mouth's center position or any other object.

Best regards,
Anthony

**Comment by auduno** [comment]
You can get the positions of the points via the function getCurrentPosition( ). See the [reference](http://auduno.github.io/clmtrackr/docs/reference.html) for more details. See the point numbering in the reference for which points to get. In case of the center of the mouth, you could get points 60 and 57 and average them to get the approximate center of the mouth.

**Comment by Anthodpnt** [comment]
Yeah indeed but there is no way to know if it's the mouth, the eye or anything else. Then it's impossible to average the X and Y position for the mouth with the getCurrentPosition function.

**Comment by auduno** [comment]
It's fully possible to know what facial points are returned, just look at the figure in the reference to understand which points are what.
