### ISSUE TITLE
Smile detection?

### ISSUE THREAD

**Issue by eduardomello** [auduno/clmtrackr#5]
Is it possible to use clmtrackr for smile detection?

**Comment by anthnyprschka** [comment]
Hi @auduno, big thanks for this super cool library :)

I think I understand how the facial landmark detection works. But how did you implement the emotion detection? Did you also train a model on labeled data for this? Or did you somehow have heuristics (something like "if the landmarks representing the eyebrows go up relatively to the rest of the landmarks, call it a "suprised emotion")?

I found the parameters of the emotionModel. But I don't know how you came up with these?

**Comment by anthnyprschka** [comment]
Ok found the other thread about this, consider my question resolved :P Thanks!
