### ISSUE TITLE
Selfie photo / emotion detection of the picture

### ISSUE THREAD

**Issue by sight011** [auduno/clmtrackr#50]
Hey,

this is aweeeesome! (I would put there even more "e"s ;) )

One question, we created some html with which we are able to shot some photos with ios and android phones on mobile webpages.

Is it possible, after having shot the photo to use your libary to detect emotion/mood of the picture?
I saw the demo for video, so probably it also works for taken pictures?

I ask because on a iOS or android phones you are not getting access to the camera directly on the mobile website only in the native camera-app. So the detection would only work out after returning back to the safari with the safed picture, right?

Is the libary based on js/webgl?
Is it possible after the detection to use some js event to show some happy/sad/angry smiley? 

Greets sight :)

**Comment by sight011** [comment]
No one?

**Comment by auduno** [comment]
Hi, emotion detection using clmtrackr should work fine for images as well, so what you describe should work. Clmtrackr uses webgl when it is available (it's faster with webgl), but works without webgl as well. It's fully possible to show a smiley after detection, but I think that's a bit outside the scope of clmtrackr :)

**Comment by sight011** [comment]
Ok, thanks for your answer!

@showing a smiley -- maybe i said it wrong. I wanted to know, if it is possible after detection to show a head which is smiling, looking angry, looking sad depending on how people are looking on their taken photo. And this i wanted to show with different smileys :) :/ :(

Possible?

**Comment by verybigelephants** [comment]
of course it's possible, just look at the examples. you can detect emotion from a single image. or what kind of help are you asking for actually?

**Comment by auduno** [comment]
Hi, if you want to show a smiley after detection, I recommend you look at the [emotion detection example](http://auduno.github.io/clmtrackr/examples/clm_emotiondetection.html) (code [here](https://github.com/auduno/clmtrackr/blob/gh-pages/examples/clm_emotiondetection.html)), which does just that.
