### ISSUE TITLE
responsive interface, changing size of video element

### ISSUE THREAD

**Issue by akinorikul** [auduno/clmtrackr#56]
Hi,

When I use clmtracker on a video element with a fix size, drawing on a canvas, it works perfectly.
But when trying to change the video element and the canvas size for a responsive html page clmtracker draws on a small part of my canvas (looks like the original dimension of the canvas) and doesn't clear outside of it.
Here an attach image for a better understanding of what I'm describing.

![clmtracker_error](https://cloud.githubusercontent.com/assets/6918264/10310232/39c316d0-6c41-11e5-8ac1-aef0db0c9f0c.jpg)

**Comment by verybigelephants** [comment]
although this is not an issue with clmtrackr and you must be resizing it wrong, why don't you post a link to your source code so we can have a look? but really, this is a stackoverflow question

**Comment by akinorikul** [comment]
you are right, there was a problem clearing my canvas. 
Sorry for the issue :(
