### ISSUE TITLE
Emotion detection not in examples directory

### ISSUE THREAD

**Issue by drpepper** [auduno/clmtrackr#60]
Hi, I just noticed that the emotion detection code is not in the `examples` directory on GitHub. It's available via the demo site, but I would think that you would want to include it in the source as well.

**Comment by cy** [comment]
change branches to the ```gh-pages``` branch https://github.com/auduno/clmtrackr/blob/gh-pages/examples%2Fclm_emotiondetection.html

**Comment by auduno** [comment]
Emotion detection code has now been moved to `examples` directory in main branches : https://github.com/auduno/clmtrackr/blob/dev/examples/clm_emotiondetection.html
