### ISSUE TITLE
Cannot load video when run locally

### ISSUE THREAD

**Issue by keanudicap** [auduno/clmtrackr#63]
I cannot load video when run locally using chrome. But it works in http://auduno.github.io/clmtrackr/clm_video.html

**Comment by post2seth** [comment]
Are you running the page in file mode? Or at localserver?

-seth
On Wednesday 2 December 2015, keanudicap <notifications@github.com> wrote:

> I cannot load video when run locally using chrome. But it works in
> http://auduno.github.io/clmtrackr/clm_video.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/auduno/clmtrackr/issues/63>.
>


-- 
Sent from Gmail iPhone App

**Comment by auduno** [comment]
Sounds like you're running the webpages directly from file. You have to run it from a local server in order for it to work, due to cross-domain restrictions in most web browsers. If you have python installed you can start a small local server in the current folder with the command ```python -m SimpleHTTPServer```.

**Comment by keanudicap** [comment]
Thank you guys. I used Xampp to set up local server and it works!
