### ISSUE TITLE
On example pages, redirect to https

### ISSUE THREAD

**Issue by xdumaine** [auduno/clmtrackr#65]
Chrome no longer supports `getUserMedia` on pages served over http, so use a simple javascript page to force over to https for the example pages.

**Comment by xdumaine** [comment]
I was going to PR this, but couldn't figure out how you were managing GH pages branch - should I modify the examples directly, or do you have a script to update the GH pages branch from dev?

**Comment by auduno** [comment]
Thanks for bringing this to my attention! I wasn't aware that Chrome had disabled getUserMedia over http already. Do you happen to know if Firefox, Safari or IE is planning to do the same thing?

I don't have a script to update gh-pages, so modifying the examples directly is fine. A bit unsure whether to enforce https via javascript in the examples though, as it won't work in most cases when serving from localhost. Maybe add an extra case for localhost? I'll update the links in the readme to point to https.

**Comment by xdumaine** [comment]
@auduno Serving from localhost is actually fine over http - it's the only exception to the HTTPS rule. So there are two options:

1. Have a code exclusion for localhost to prevent the https redirect, or 
2. Add simple instructions for serving localhost over https.

I can help with either. My preferred method is 2, and I have a couple different very simple methods for this if you're interested.

**Comment by auduno** [comment]
After some thought, I think we need to add a script to redirect to https as you suggested. I think it's fine to add an exclusion for localhost, i.e.
```
if (window.location.hostname !== "localhost" && window.location.protocol !== "https:"){
  window.location.protocol = "https";
}
```
but which methods do you suggest for serving localhost over https?

**Comment by xdumaine** [comment]
My favorite is a simple little npm tool called `stupid-server` - you just `npm install -g stupid server && stupid-server -s` then you can open up `https://localhost:8443` - alternatively, you could include a script directly in your repo for users to use when developing. Something like this - https://github.com/xdumaine/stupid-simple-node-server/blob/master/index.js
