### ISSUE TITLE
Tracking multiple faces

### ISSUE THREAD

**Issue by manorius** [auduno/clmtrackr#7]
Hi,

Is it possible to detect and get information about two faces at the same time? 

thanks

**Comment by verybigelephants** [comment]
hmm, isn't the face tracking using viola-jones tracking of haar-like features? meaning it will detect ALL the present faces in an image - this is the most resource hungry process by the way. then you would only have to keep track of the face models in some array. this is definitely a valid feature request

**Comment by auduno** [comment]
@verybigelephants : it's very possible to *detect* multiple faces using viola-jones, but it's not precise enough to track facial points. The method I use in clmtrackr is unfortunately very computationally demanding, so I don't think it will work very well for multiple faces. But it's worth a try if someone wants to give it a shot!

**Comment by jb41997** [comment]
I just started using clmtrackr (and am very impressed btw)...but I too would be interested in multiple face functionality.  I realize tracking multiples would be too resource intensive for some computers/devices...so...how hard would it be to at least **detect** multiple faces and expose that to the api so we could cycle through them or manually choose which one to track?

**Comment by jb41997** [comment]
@verybigelephants being able to detect them is all that I would really need.  I can probably work around the need to track features of multiples.  Tracking features of multiples would be awesome but I realize there are resource limitations, so I won't get my hopes up on that one.  (are there already methods in this library that allow you to detect multiples?)

**Comment by dehuszar** [comment]
I noticed that various functions can get passed an element and a box.  [For instance](https://github.com/auduno/clmtrackr/blob/dev/clmtrackr.js#L310).  Without any docs to say otherwise, it seems like the box might be a specific set of dimensions to scan within an image or video.  Is that correct?

**Comment by verybigelephants** [comment]
well you could of course user part of the clmtrack but i think if just detecting face positions is the question, there are other libraries designed specifically for this task 

https://github.com/jaysalvat/jquery.facedetection
https://github.com/eduardolundgren/tracking.js
(and many others i believe)

**Comment by hyzhak** [comment]
so what about such scenario:
