### ISSUE TITLE
Some code issues

### ISSUE THREAD

**Issue by wvdvegt** [auduno/clmtrackr#77]
Hi,

When the mossefilter is not present, the code in getInitialPosition fails at line 1158/59 and 1167. 
Both xmin, ymin are never defined and rotation is never calculated in this code block.

**Comment by auduno** [comment]
Thanks for reporting this issue! This has now been fixed [here](https://github.com/auduno/clmtrackr/commit/d5a1cb0ef6df5aa29f7ea793819bd1abff637629).
