### ISSUE TITLE
About the version tag

### ISSUE THREAD

**Issue by x09326** [auduno/clmtrackr#79]
Hi, I'm going to host this lib on [cdnjs](https://cdnjs.com).

Can you add the version tag?
It will help me to add the auto-update config.

Thanks!
https://github.com/cdnjs/cdnjs/issues/7953

**Comment by auduno** [comment]
Hi, sorry for late reply, I've added a version tag now, and will update it when there are any changes. Thanks for hosting it on cdnjs!
