### ISSUE TITLE
Please add this project to NPM registry

### ISSUE THREAD

**Issue by leosuncin** [auduno/clmtrackr#90]
It would be very nice if you add this project to NPM registry, this will be more easy to add as dependency in a project throught `npm install --save`

You can find the instructions here https://gist.github.com/coolaj86/1318304 it not will be difficult just update you `package.json` and some commands

**Comment by leosuncin** [comment]
Because now I get an error if run ``npm i -S git://github.com/auduno/clmtrackr.git#dev``
```bash
npm ERR! addLocal Could not install /tmp/npm-31755-ac886e0b/git-cache-c8faa6b5/3b4d93838cef8694229c1280a323ab54103d4919
npm ERR! Linux 4.4.31-1-MANJARO
npm ERR! argv "/usr/bin/node" "/usr/sbin/npm" "i" "-S" "git://github.com/auduno/clmtrackr.git#dev"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9

npm ERR! No name provided in package.json
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/Workspaces/virtual-goggle-tester/npm-debug.log
```

**Comment by sibelius** [comment]
@auduno it would be really good to have this project on npm

**Comment by auduno** [comment]
This project is now on npm : https://www.npmjs.com/package/clmtrackr
