### ISSUE TITLE
Is there a way to analyse an image, not a video?

### ISSUE THREAD

**Issue by AmitMY** [auduno/clmtrackr#94]
For a project, I need to analyse images for facial features. I wondered if this library is able to do so, and not just videos.
The best solution I have so far is to create a video with the image moving left-to-right, and rotating left-to-right, up-and-down. but that is dirty.

**Comment by auduno** [comment]
It is possible to use images as well, take a look at some of the examples, for instance this : https://auduno.github.io/clmtrackr/clm_image.html

**Comment by AmitMY** [comment]
Odd.
I was using this image for testing:
![1](https://cloud.githubusercontent.com/assets/5757359/21497050/4f2ac234-cc2b-11e6-9b1e-e07e5d4ca988.jpg)

Sometimes it converges, but not really and sometimes it fails.
![image](https://cloud.githubusercontent.com/assets/5757359/21497043/4719b320-cc2b-11e6-8d2a-36d958dd8fe1.png)

And locally, the results is quite funny:
![image](https://cloud.githubusercontent.com/assets/5757359/21497094/88f9a0fc-cc2b-11e6-9668-19778e44f44d.png)
