### ISSUE TITLE
Z coordinate?

### ISSUE THREAD

**Issue by AmitMY** [auduno/clmtrackr#95]
When getting featurepoints, the format is:
`featurepoint i : [x,y]`

There seem to be applied 2 axis rotation on a model, so I was wondering if it is at all possible to get a "z" value for the face mask feature point? 

(I know it sounds a bit ridicules, but I just feel like there is a Z value for each of the points)

**Comment by auduno** [comment]
If by z-value mean a depth point, i.e. a 3D-model, I'm afraid not, this is only a 2D-model.
